CREATE TABLE IF NOT EXISTS tenants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  code VARCHAR(50) UNIQUE NOT NULL,
  subdomain VARCHAR(100) UNIQUE,
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active','suspended','pending','disabled')),
  server_url VARCHAR(255) NOT NULL,
  server_ip VARCHAR(45),
  database_name VARCHAR(100),
  instance_version VARCHAR(20) DEFAULT '1.0.0',
  plan_type VARCHAR(50) DEFAULT 'basic' CHECK (plan_type IN ('basic','standard','premium','enterprise')),
  subscription_id VARCHAR(100),
  subscription_status VARCHAR(20) DEFAULT 'active',
  subscription_start_date DATE,
  subscription_end_date DATE,
  monthly_price DECIMAL(10,2) DEFAULT 0.00,
  max_users INTEGER DEFAULT 50,
  max_students INTEGER DEFAULT 500,
  max_storage_mb INTEGER DEFAULT 1024,
  allowed_modules JSONB DEFAULT '[]',
  enabled_features JSONB DEFAULT '[]',
  admin_email VARCHAR(255),
  admin_name VARCHAR(255),
  admin_phone VARCHAR(20),
  school_address TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_sync_at TIMESTAMP,
  notes TEXT
);
